<?php

namespace ContainerQVOkxKE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_GH1cYuFService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.GH1cYuF' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.GH1cYuF'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'converter' => ['privates', 'App\\Service\\ExchangeRateConverter', 'getExchangeRateConverterService', true],
        ], [
            'converter' => 'App\\Service\\ExchangeRateConverter',
        ]);
    }
}
