<?php

namespace ContainerLCm5835;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getExchangeRateConverterService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\ExchangeRateConverter' shared autowired service.
     *
     * @return \App\Service\ExchangeRateConverter
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'ExchangeRateConverter.php';

        return $container->privates['App\\Service\\ExchangeRateConverter'] = new \App\Service\ExchangeRateConverter(($container->privates['http_client'] ?? $container->load('getHttpClientService')));
    }
}
