<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQVOkxKE\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQVOkxKE/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerQVOkxKE.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerQVOkxKE\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerQVOkxKE\App_KernelDevDebugContainer([
    'container.build_hash' => 'QVOkxKE',
    'container.build_id' => 'd41e3d07',
    'container.build_time' => 1655879267,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQVOkxKE');
